export const DISTRIBUTION_CALCULATION_VERSION = "distribution-v1";

export const BASIS_POINTS_DENOMINATOR = 10_000;

export const MAX_ALLOCATION_BASIS_POINTS = 10_000;

export const MIN_ALLOCATION_BASIS_POINTS = 0;
